### ISSUE TITLE
Reference Value Provider Service Crate

### ISSUE THREAD

**Issue by Xynnn007** [confidential-containers/kbs#210]
As the proposal https://github.com/confidential-containers/confidential-containers/issues/122,
RVPS is a key component for AS to gather the `trusted digests`. TODO list here

#### Stage 1

- [x] Define the trusted digest format between AS and RVPS
- [x] Implement RVPS as a crate
https://github.com/confidential-containers/attestation-service/pull/13
- [x] Implement a local file storage as Cache
https://github.com/confidential-containers/attestation-service/pull/17
- [x] Implement in-toto as a provenance type & test
https://github.com/confidential-containers/kbs/issues/207
- [x] Documentation and binary
https://github.com/confidential-containers/attestation-service/pull/47
- [x] Integrate RVPS into AS
https://github.com/confidential-containers/attestation-service/pull/26

#### Optimization
- [x] Async & Stream
https://github.com/confidential-containers/attestation-service/pull/47
